<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYZP3FR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYZP3FR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTYZP3FR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTYZP3FR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTYZP3FR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TYZP3FR',
    'container.build_id' => '1b544590',
    'container.build_time' => 1602149180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYZP3FR');
